export {Header} from './Header/header';
export {Navbar} from './Header/navbar'
export {About} from './about';
export {HeaderInput} from './Header/header-input';
export {Categories} from './categories'
export {Filter} from './filter';
export {ProductsCards} from './products-cards';
export {Paginations} from './paginations';
export {Footer} from './footer'