import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google"

// import { Header } from "@/components/shared";


import { Footer, Navbar } from "@/components/shared";

const monserta = Montserrat({
  subsets: ['cyrillic'],
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700', '800', '900'],
})




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserta.variable}  antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
